### ISSUE TITLE
http://iso.org/25012/2008/dataquality/ value node skal ikke plasseres mellom "<" og ">"

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-harvester-bff#26]
https://data.norge.no/datasets/68d08f28-a16d-4fab-a953-ed4ab08ce2e2

```
dqv:hasQualityAnnotation        [ a                dqv:QualityAnnotation ;
                                          dqv:inDimension  <iso:Currentness> ;
                                          prov:hasBody     [ rdf:value  "Antall ansatte oppdateres ca. den 10. hver måned. \nMVA oppdateres en gang i døgnet.\nDaglig oppdatering fra Folkeregisteret og Matrikkelen."@nb ]
                                        ] ;
dqv:hasQualityAnnotation        [ a                dqv:QualityAnnotation ;
                                  dqv:inDimension  <iso:Completeness> ;
                                  prov:hasBody     [] 
                                ] .
```

**Comment by stigbd** [comment]
Relevante stader i spekken er her:
https://data.norge.no/specification/dqv-ap-no/#Kvalitetsnote_erIKvalitetsdimensjon

**Comment by stigbd** [comment]
Relevante stader i spekken er her:
https://data.norge.no/specification/dqv-ap-no/#Kvalitetsnote_erIKvalitetsdimensjon

**Comment by stigbd** [comment]
@jimjyang Kan du ta ein kik på dette? Eg ser feks at dqv-ap-no sine eksempler hentar range frå dqvno.

**Comment by jeffreiffers** [comment]
Om node value er url resurs så skal den plasseres mellom <> så tror det faktisk er riktig som det er nå.

**Comment by stigbd** [comment]
Eksemplet i dqv-ap-no ser slik ut:
```
:aQAnnotation
   a dqv:QualityAnnotation ;
   oa:motivatedBy dqv:qualityAssessment ;
   dqv:inDimension dqvno:completeness .
```

**Comment by jimjyang** [comment]
Jo, det skal plasseres mellom "<" og ">". Det som pekes på skal være en instans av dqv:Dimension.

**Comment by jimjyang** [comment]
Jo, det skal plasseres mellom "<" og ">". Det som pekes på skal være en instans av dqv:Dimension.

**Comment by jimjyang** [comment]
Jo, det skal plasseres mellom "<" og ">". Det som pekes på skal være en instans av dqv:Dimension.

**Comment by jeffreiffers** [comment]
Ok da lukker jeg denne.

**Comment by jimjyang** [comment]
Sorry, jeg forstod feil. Det skal _ikke_ være <> rundt iso:Completeness, siden iso:Completeness er en IRI (med @prefix iso:   <http://iso.org/25012/2008/dataquality/>).

**Comment by jeffreiffers** [comment]
URIs are resolved relative to the In-scope base URI.

The starting In-Scope Base URI is defined using the Base URI mechanism defined in the URI RFC - dependent on the protocol or other context outside the document. During turtle parsing, the in-scope base URI at any point in the document is determined by the @base directive which sets a new base URI relative to the current in-scope base URI. This directive may be repeated.

Example (test-30.ttl) with document base URI http://www.w3.org/2001/sw/DataAccess/df1/tests/
```
# In-scope base URI is http://www.w3.org/2001/sw/DataAccess/df1/tests/ at this point
<test-00.ttl> <test-01.ttl> <test-02.ttl> .
@base <http://example.org/ns/> .
# In-scope base URI is http://example.org/ns/ at this point
<a2> <http://example.org/ns/b2> <c2> .
@base <foo/> .
# In-scope base URI is http://example.org/ns/foo/ at this point
<a3> <b3> <c3> .
@prefix : <bar#> .
:a4 :b4 :c4 .
@prefix : <http://example.org/ns2#> .
:a5 :b5 :c5 .
```

**Comment by jeffreiffers** [comment]
Så er lov men da må man bruke @base.

**Comment by jimjyang** [comment]
> Så er lov men da må man bruke @base.

Tror det blir feil med base _og_ "iso:" foran, eller?

**Comment by jeffreiffers** [comment]
Ja kan ikke bruke base og prefix såvidt jeg vet.

**Comment by JoachimFugleberg** [comment]
Om jeg husker dette rette er det fullt mulig å bruke @base, men ikke samtidig som "@prefix". Aner ikke om base eller prefix vil brukes av motoren, eventuelt om iso:Completness bare blir en streng.

@base <https://www.iso.org/25012/2008/dataquality/>.

dqv:hasQualityAnnotation        [ a                dqv:QualityAnnotation ;
                                  dqv:inDimension  <Completeness> ;
                                  prov:hasBody     [] 
                                ] .


Løses opp til:
<https://www.w3.org/TR/vocab-dqv/#dqvhasQualityAnnotation> <https://www.w3.org/TR/vocab-dqv/#dqvinDimension> <https://www.iso.org/25012/2008/dataquality/Completeness> .

**Comment by jimjyang** [comment]
Takk, @JoachimFugleberg! Det var det jeg tenkte, dvs. hvis @base brukes, så skal det ikke stå <iso:Completeness>, men <Completeness>.  

Hvis @prefix brukes, så skal det stå iso:Completeness uten <> rundt. 

Jeg tror derfor at det uansett er feil i dette datasettet.

**Comment by stigbd** [comment]
@jeffreiffers Gjorde vi noko for at dette skulle bli korrekt, eller var det ingen feil?
