### ISSUE TITLE
Begrepskatalog apiet går for tregt

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-harvester-bff#37]
Dette er eksempelet fra Brreg hvor begrepene bruker opptil 10 sekunder på å laste https://data.brreg.no/kompensasjonsordning/innsyn/

Forslag:

1. BR kan cache på sin side
2. Vi kan cache (reverse-proxy i nginx)
3. Vi kan lage en cache i tjenesten

Antageligvis bør vi gå for en kombinasjon av 1 og 2 på kortsikt.

**Comment by stigbd** [comment]
Eg har oppretta repo for reverse-proxy:
https://github.com/Informasjonsforvaltning/fdk-nginx-harvester-bff

**Comment by shenluna** [comment]
Testet på https://data.brreg.no/kompensasjonsordning/innsyn/ nå vises begrepene med engang.
